Game client
vieirafrancisco/pong pull request #10
Opened 2020-11-20 19:53 UTC by vieirafrancisco

Pull request criado para resolver a issue #4

2020-11-21 12:52 UTC, jadsonlucio requested changes

2020-11-21 12:52 UTC, jadsonlucio commented on pong/client/pong_client.py
> +                self.game.score[0]+=1
Acho que essa parte tem que ficar no game francisco, pq iria quebrar se a gente removesse o cliente.

2020-11-21 15:16 UTC, vieirafrancisco commented on pong/client/pong_client.py
> +                self.game.score[0]+=1
Beleza

2020-11-26 14:20 UTC, jadsonlucio approved these changes

2020-11-26 14:21 UTC, merged